- src: http://github.com/websoft9dev/role_common

- src: http://github.com/websoft9dev/role_cloud

- src: http://github.com/websoft9dev/role_nginx

# 根据需求添加相对应的role

- src: http://github.com/websoft9dev/role_preend

- src: http://github.com/websoft9dev/role_end
